updated dockerfile

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,6 +1,12 @@
-FROM archlinux:base-devel
+## SPDX-License-Identifier: MIT OR Apache-2.0
+##
+## Copyright (c) 2017-2022 Andre Richter <andre.o.richter@gmail.com>
+## Copyright (c) 2019-2022 Nao Taco <naotaco@gmail.com>
+FROM ubuntu:20.04
 
 ARG VCS_REF
+ARG GCC_AARCH64=https://developer.arm.com/-/media/Files/downloads/gnu-a/10.3-2021.07/binrel/gcc-arm-10.3-2021.07-aarch64-aarch64-none-elf.tar.xz
+ARG GCC_X86_64=https://developer.arm.com/-/media/Files/downloads/gnu-a/10.3-2021.07/binrel/gcc-arm-10.3-2021.07-x86_64-aarch64-none-elf.tar.xz
 
 LABEL org.label-schema.vcs-ref=$VCS_REF \
     org.label-schema.vcs-url="https://github.com/jewlexx/do-not-enter"
@@ -10,38 +16,56 @@ LABEL maintainer="Juliette Cordor"
 # Ruby gems
 COPY Gemfile .
 
-RUN pacman -Syyu --noconfirm \
+RUN set -ex;                                      \
+    tempPkgs='                                    \
     automake                                  \
     bison                                     \
+    build-essential                           \
     flex                                      \
+    git                                       \
     libtool                                   \
-    ninja                          \
+    ninja-build                               \
     pkg-config                                \
     wget                                      \
+    ';                                            \
+    apt-get update;                               \
+    apt-get install -q -y --no-install-recommends \
+    $tempPkgs                                 \
     # persistent packages
     ca-certificates                           \
-    pixman                           \
-    glib2 \
-    libusb                          \
+    gdb-multiarch                             \
+    libpixman-1-dev                           \
+    libglib2.0-dev                            \
+    libusb-1.0.0-dev                          \
+    locales                                   \
     python3                                   \
     ruby                                      \
-    ;
-RUN mkdir /tmp/multi; \
-    chmod 777 /tmp/multi; \
-    git clone https://aur.archlinux.org/gdb-multiarch.git /tmp/multi; \
-    export OLD_WD=$PWD; \
-    cd /tmp/multi; \
-    makepkg -si --noconfirm; \
-    rm -rf *; \
-    git clone https://aur.archlinux.org/aarch64-none-elf-toolchain.git; \
-    makepkg -si --noconfirm; \
-    cd $OLD_WD;
-# Ruby dependencies
-RUN gem install bundler;                             \
+    ruby-dev                                  \
+    ;                                             \
+    # GCC AArch64 tools
+    if [ "$(uname -m)" = "aarch64" ]; then wget ${GCC_AARCH64}; else wget ${GCC_X86_64}; fi; \
+    tar -xf gcc-arm-10*;                                                                     \
+    cp                                                                                       \
+    gcc-arm-10*/bin/aarch64-none-elf-objdump                                             \
+    gcc-arm-10*/bin/aarch64-none-elf-readelf                                             \
+    gcc-arm-10*/bin/aarch64-none-elf-nm                                                  \
+    /usr/local/bin/;                                                                     \
+    rm -rf gcc-arm-10*;                                                                      \
+    # Ruby dependencies
+    gem install bundler;                             \
     bundle config set --local without 'development'; \
     bundle install --retry 3;                        \
     # QEMU
-    pacman -S qemu-full --noconfirm;                                     \
+    git clone https://gitlab.com/qemu-project/qemu.git;        \
+    cd qemu;                                                   \
+    git checkout tags/v6.1.0;                                  \
+    ./configure --target-list=aarch64-softmmu --enable-modules \
+    --enable-tcg-interpreter --enable-debug-tcg            \
+    --python=/usr/bin/python3;                             \
+    make -j10;                                                 \
+    make install;                                              \
+    cd ..;                                                     \
+    rm -rf qemu;                                               \
     # Openocd
     git clone --depth 1 https://git.code.sf.net/p/openocd/code openocd; \
     cd openocd;                                                         \
@@ -50,7 +74,12 @@ RUN gem install bundler;                             \
     make -j10;                                                          \
     make install;                                                       \
     # GDB
-    wget -P ~ git.io/.gdbinit;
+    wget -P ~ git.io/.gdbinit; \
+    # Cleanup
+    apt-get purge -y --auto-remove $tempPkgs; \
+    apt-get autoremove -q -y;                 \
+    apt-get clean -q -y;                      \
+    rm -rf /var/lib/apt/lists/*
 
 # Locales
 RUN locale-gen en_US.UTF-8
