updated dockerfile

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,4 +1,4 @@
-FROM ubuntu:20.04
+FROM alpine:3.15.5
 
 ARG VCS_REF
 ARG GCC_AARCH64=https://developer.arm.com/-/media/Files/downloads/gnu-a/10.3-2021.07/binrel/gcc-arm-10.3-2021.07-aarch64-aarch64-none-elf.tar.xz
@@ -12,70 +12,54 @@ LABEL maintainer="Juliette Cordor"
 # Ruby gems
 COPY Gemfile .
 
-RUN set -ex;                                      \
-    apt-get update;                               \
-    apt-get install -q -y --no-install-recommends \
+RUN set -ex;                                  \
+    apk update;                               \
+    apk upgrade;                              \
+    apk add                                   \
     automake                                  \
     bison                                     \
-    build-essential                           \
+    alpine-sdk                                \
     flex                                      \
     git                                       \
     libtool                                   \
-    ninja-build                               \
-    pkg-config                                \
+    ninja                                     \
+    pkgconfig                                 \
     wget                                      \
-    # persistent packages
+    qemu-system-aarch64                       \
     ca-certificates                           \
     gdb-multiarch                             \
-    libpixman-1-dev                           \
-    libglib2.0-dev                            \
-    libusb-1.0.0-dev                          \
-    locales                                   \
+    pixman                                    \
+    glib                                      \
+    libusb                                    \
     python3                                   \
     ruby                                      \
     ruby-dev                                  \
-    ;                                         \
-    # GCC AArch64 tools
-    if [ "$(uname -m)" = "aarch64" ]; then wget ${GCC_AARCH64}; else wget ${GCC_X86_64}; fi; \
-    tar -xf gcc-arm-10*;                                                                     \
-    cp                                                                                       \
-    gcc-arm-10*/bin/aarch64-none-elf-objdump                                             \
-    gcc-arm-10*/bin/aarch64-none-elf-readelf                                             \
-    gcc-arm-10*/bin/aarch64-none-elf-nm                                                  \
-    /usr/local/bin/;                                                                     \
-    rm -rf gcc-arm-10*;                                                                      \
-    # Ruby dependencies
-    gem install bundler;                             \
+    gcc-aarch64-none-elf                      \
+    openocd
+
+# Ruby dependencies
+RUN gem install bundler;                             \
     bundle config set --local without 'development'; \
     bundle install --retry 3;                        \
-    # QEMU
-    git clone https://gitlab.com/qemu-project/qemu.git;        \
-    cd qemu;                                                   \
-    git checkout tags/v6.1.0;                                  \
-    ./configure --target-list=aarch64-softmmu --enable-modules \
-    --enable-tcg-interpreter --enable-debug-tcg            \
-    --python=/usr/bin/python3;                             \
-    make -j10;                                                 \
-    make install;                                              \
-    cd ..;                                                     \
-    rm -rf qemu;                                               \
-    # Openocd
-    git clone --depth 1 https://git.code.sf.net/p/openocd/code openocd; \
-    cd openocd;                                                         \
-    ./bootstrap;                                                        \
-    ./configure --enable-ftdi;                                          \
-    make -j10;                                                          \
-    make install;                                                       \
     # GDB
-    wget -P ~ git.io/.gdbinit; \
-    # Cleanup
-    apt-get purge -y --auto-remove $tempPkgs; \
-    apt-get autoremove -q -y;                 \
-    apt-get clean -q -y;                      \
-    rm -rf /var/lib/apt/lists/*
+    wget -P ~ git.io/.gdbinit
 
 # Locales
-RUN locale-gen en_US.UTF-8
+ENV MUSL_LOCALE_DEPS cmake make musl-dev gcc gettext-dev libintl
+ENV MUSL_LOCPATH /usr/share/i18n/locales/musl
+
+RUN apk add \
+    $MUSL_LOCALE_DEPS \
+    && wget https://gitlab.com/rilian-la-te/musl-locales/-/archive/master/musl-locales-master.zip \
+    && unzip musl-locales-master.zip \
+    && cd musl-locales-master \
+    && cmake -DLOCALE_PROFILE=OFF -D CMAKE_INSTALL_PREFIX:PATH=/usr . && make && make install \
+    && cd .. && rm -r musl-locales-master
+
+# Cleanup
+RUN apk del $MUSL_LOCALE_DEPS; \
+    rm -rf /var/cache/apk/*
+
 
 ENV LANG=en_US.UTF-8   \
     LANGUAGE=en_US:en  \
